/**
 * Canonical field ontology — 50+ fields covering all 8 template families.
 * Each field maps to a standardized financial concept with hierarchy and formula rules.
 */

export interface CanonicalFieldDef {
  canonicalField: string;
  displayName: string;
  statementType: string;
  fieldGroup: string;
  parentField: string | null;
  formulaRule: string | null;
  supportedTemplates: string[];
}

export const CANONICAL_FIELDS: CanonicalFieldDef[] = [
  // ── Income Statement ──────────────────────────────────────
  {
    canonicalField: 'total_revenue',
    displayName: 'Total Revenue / Turnover',
    statementType: 'income_statement',
    fieldGroup: 'revenue',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'interest_income',
    displayName: 'Interest Income',
    statementType: 'income_statement',
    fieldGroup: 'revenue',
    parentField: 'total_revenue',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T7', 'T8'],
  },
  {
    canonicalField: 'fee_income',
    displayName: 'Fee and Commission Income',
    statementType: 'income_statement',
    fieldGroup: 'revenue',
    parentField: 'total_revenue',
    formulaRule: null,
    supportedTemplates: ['T3', 'T7', 'T8'],
  },
  {
    canonicalField: 'commission_income',
    displayName: 'Commission / Brokerage Income',
    statementType: 'income_statement',
    fieldGroup: 'revenue',
    parentField: 'total_revenue',
    formulaRule: null,
    supportedTemplates: ['T8'],
  },
  {
    canonicalField: 'other_operating_income',
    displayName: 'Other Operating Income',
    statementType: 'income_statement',
    fieldGroup: 'revenue',
    parentField: 'total_revenue',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T5', 'T8'],
  },
  {
    canonicalField: 'other_income',
    displayName: 'Other Income',
    statementType: 'income_statement',
    fieldGroup: 'revenue',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'total_income',
    displayName: 'Total Income',
    statementType: 'income_statement',
    fieldGroup: 'revenue',
    parentField: null,
    formulaRule: 'total_revenue + other_income',
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'cost_of_sales',
    displayName: 'Cost of Sales / Cost of Revenue',
    statementType: 'income_statement',
    fieldGroup: 'expenses',
    parentField: 'total_expenses',
    formulaRule: null,
    supportedTemplates: ['T1', 'T4', 'T5'],
  },
  {
    canonicalField: 'gross_profit',
    displayName: 'Gross Profit',
    statementType: 'income_statement',
    fieldGroup: 'profitability',
    parentField: null,
    formulaRule: 'total_revenue - cost_of_sales',
    supportedTemplates: ['T1', 'T4', 'T5'],
  },
  {
    canonicalField: 'admin_expenses',
    displayName: 'Administration Expenses',
    statementType: 'income_statement',
    fieldGroup: 'expenses',
    parentField: 'total_expenses',
    formulaRule: null,
    supportedTemplates: ['T1', 'T5', 'T6', 'T7'],
  },
  {
    canonicalField: 'finance_costs',
    displayName: 'Finance Costs / Interest Expense',
    statementType: 'income_statement',
    fieldGroup: 'expenses',
    parentField: 'total_expenses',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T5', 'T7', 'T8'],
  },
  {
    canonicalField: 'impairment_charge',
    displayName: 'Impairment on Financial Instruments',
    statementType: 'income_statement',
    fieldGroup: 'expenses',
    parentField: 'total_expenses',
    formulaRule: null,
    supportedTemplates: ['T3', 'T7', 'T8'],
  },
  {
    canonicalField: 'employee_benefits_expense',
    displayName: 'Employee Benefits Expense',
    statementType: 'income_statement',
    fieldGroup: 'expenses',
    parentField: 'total_expenses',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T5', 'T8'],
  },
  {
    canonicalField: 'depreciation_amortization',
    displayName: 'Depreciation and Amortization',
    statementType: 'income_statement',
    fieldGroup: 'expenses',
    parentField: 'total_expenses',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T4', 'T5', 'T8'],
  },
  {
    canonicalField: 'total_expenses',
    displayName: 'Total Expenses',
    statementType: 'income_statement',
    fieldGroup: 'expenses',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'operating_income',
    displayName: 'Operating Profit / (Loss)',
    statementType: 'income_statement',
    fieldGroup: 'profitability',
    parentField: null,
    formulaRule: 'total_income - total_expenses',
    supportedTemplates: ['T1', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'profit_before_tax',
    displayName: 'Profit / (Loss) Before Tax',
    statementType: 'income_statement',
    fieldGroup: 'profitability',
    parentField: null,
    formulaRule: 'total_income - total_expenses',
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'income_tax_expense',
    displayName: 'Income Tax Expense',
    statementType: 'income_statement',
    fieldGroup: 'tax',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T7', 'T8'],
  },
  {
    canonicalField: 'net_income',
    displayName: 'Net Income / Profit for the Year',
    statementType: 'income_statement',
    fieldGroup: 'profitability',
    parentField: null,
    formulaRule: 'profit_before_tax - income_tax_expense',
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'other_comprehensive_income',
    displayName: 'Other Comprehensive Income',
    statementType: 'income_statement',
    fieldGroup: 'profitability',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T8'],
  },
  {
    canonicalField: 'total_comprehensive_income',
    displayName: 'Total Comprehensive Income',
    statementType: 'income_statement',
    fieldGroup: 'profitability',
    parentField: null,
    formulaRule: 'net_income + other_comprehensive_income',
    supportedTemplates: ['T1', 'T3', 'T8'],
  },
  {
    canonicalField: 'eps_basic',
    displayName: 'Earnings Per Share — Basic',
    statementType: 'income_statement',
    fieldGroup: 'per_share',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T4'],
  },
  {
    canonicalField: 'eps_diluted',
    displayName: 'Earnings Per Share — Diluted',
    statementType: 'income_statement',
    fieldGroup: 'per_share',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T4'],
  },
  {
    canonicalField: 'members_remuneration',
    displayName: "Members' Remuneration",
    statementType: 'income_statement',
    fieldGroup: 'expenses',
    parentField: 'total_expenses',
    formulaRule: null,
    supportedTemplates: ['T6'],
  },
  {
    canonicalField: 'capital_allocation_income',
    displayName: 'Capital Allocation Based Income',
    statementType: 'income_statement',
    fieldGroup: 'revenue',
    parentField: 'total_revenue',
    formulaRule: null,
    supportedTemplates: ['T2'],
  },
  {
    canonicalField: 'carried_interest',
    displayName: 'Carried Interest / Performance Allocation',
    statementType: 'income_statement',
    fieldGroup: 'revenue',
    parentField: 'total_revenue',
    formulaRule: null,
    supportedTemplates: ['T2'],
  },
  {
    canonicalField: 'securities_lending_income',
    displayName: 'Securities Lending Income',
    statementType: 'income_statement',
    fieldGroup: 'revenue',
    parentField: 'total_revenue',
    formulaRule: null,
    supportedTemplates: ['T8'],
  },

  // ── Balance Sheet ─────────────────────────────────────────
  {
    canonicalField: 'total_assets',
    displayName: 'Total Assets',
    statementType: 'balance_sheet',
    fieldGroup: 'assets',
    parentField: null,
    formulaRule: 'current_assets + non_current_assets',
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'current_assets',
    displayName: 'Total Current Assets',
    statementType: 'balance_sheet',
    fieldGroup: 'assets',
    parentField: 'total_assets',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T5', 'T8'],
  },
  {
    canonicalField: 'non_current_assets',
    displayName: 'Total Non-Current Assets',
    statementType: 'balance_sheet',
    fieldGroup: 'assets',
    parentField: 'total_assets',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T5', 'T8'],
  },
  {
    canonicalField: 'cash_and_equivalents',
    displayName: 'Cash and Cash Equivalents',
    statementType: 'balance_sheet',
    fieldGroup: 'assets',
    parentField: 'current_assets',
    formulaRule: null,
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'trade_receivables',
    displayName: 'Trade and Other Receivables',
    statementType: 'balance_sheet',
    fieldGroup: 'assets',
    parentField: 'current_assets',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T5', 'T7', 'T8'],
  },
  {
    canonicalField: 'loans_and_advances',
    displayName: 'Loans and Advances',
    statementType: 'balance_sheet',
    fieldGroup: 'assets',
    parentField: 'non_current_assets',
    formulaRule: null,
    supportedTemplates: ['T3', 'T7'],
  },
  {
    canonicalField: 'property_plant_equipment',
    displayName: 'Property, Plant and Equipment',
    statementType: 'balance_sheet',
    fieldGroup: 'assets',
    parentField: 'non_current_assets',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T4', 'T5', 'T8'],
  },
  {
    canonicalField: 'clearing_funds',
    displayName: 'Clearing Settlement Funds',
    statementType: 'balance_sheet',
    fieldGroup: 'assets',
    parentField: 'current_assets',
    formulaRule: null,
    supportedTemplates: ['T8'],
  },
  {
    canonicalField: 'total_liabilities',
    displayName: 'Total Liabilities',
    statementType: 'balance_sheet',
    fieldGroup: 'liabilities',
    parentField: null,
    formulaRule: 'current_liabilities + non_current_liabilities',
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'current_liabilities',
    displayName: 'Total Current Liabilities',
    statementType: 'balance_sheet',
    fieldGroup: 'liabilities',
    parentField: 'total_liabilities',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T5', 'T8'],
  },
  {
    canonicalField: 'non_current_liabilities',
    displayName: 'Total Non-Current Liabilities',
    statementType: 'balance_sheet',
    fieldGroup: 'liabilities',
    parentField: 'total_liabilities',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T5', 'T8'],
  },
  {
    canonicalField: 'borrowings',
    displayName: 'Borrowings / Debt',
    statementType: 'balance_sheet',
    fieldGroup: 'liabilities',
    parentField: 'total_liabilities',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T4', 'T7', 'T8'],
  },
  {
    canonicalField: 'total_equity',
    displayName: 'Total Equity / Shareholders Funds',
    statementType: 'balance_sheet',
    fieldGroup: 'equity',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'share_capital',
    displayName: 'Share Capital / Paid-up Capital',
    statementType: 'balance_sheet',
    fieldGroup: 'equity',
    parentField: 'total_equity',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T4', 'T5', 'T8'],
  },
  {
    canonicalField: 'retained_earnings',
    displayName: 'Retained Earnings / Accumulated Profits',
    statementType: 'balance_sheet',
    fieldGroup: 'equity',
    parentField: 'total_equity',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T4', 'T5', 'T8'],
  },
  {
    canonicalField: 'partners_capital',
    displayName: "Partners' / Members' Capital",
    statementType: 'balance_sheet',
    fieldGroup: 'equity',
    parentField: 'total_equity',
    formulaRule: null,
    supportedTemplates: ['T2', 'T6'],
  },
  {
    canonicalField: 'statutory_reserve_rbi',
    displayName: 'Statutory Reserve u/s 45-IC RBI',
    statementType: 'balance_sheet',
    fieldGroup: 'equity',
    parentField: 'total_equity',
    formulaRule: null,
    supportedTemplates: ['T3'],
  },
  {
    canonicalField: 'non_controlling_interests',
    displayName: 'Non-Controlling Interests',
    statementType: 'balance_sheet',
    fieldGroup: 'equity',
    parentField: 'total_equity',
    formulaRule: null,
    supportedTemplates: ['T1', 'T2', 'T8'],
  },

  // ── Cash Flow Statement ───────────────────────────────────
  {
    canonicalField: 'cash_from_operations',
    displayName: 'Net Cash from Operating Activities',
    statementType: 'cash_flow',
    fieldGroup: 'operating',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'cash_from_investing',
    displayName: 'Net Cash from Investing Activities',
    statementType: 'cash_flow',
    fieldGroup: 'investing',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'cash_from_financing',
    displayName: 'Net Cash from Financing Activities',
    statementType: 'cash_flow',
    fieldGroup: 'financing',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'cash_start',
    displayName: 'Cash at Beginning of Period',
    statementType: 'cash_flow',
    fieldGroup: 'balance',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'cash_end',
    displayName: 'Cash at End of Period',
    statementType: 'cash_flow',
    fieldGroup: 'balance',
    parentField: null,
    formulaRule: 'cash_start + cash_from_operations + cash_from_investing + cash_from_financing',
    supportedTemplates: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'],
  },
  {
    canonicalField: 'interest_received_investing',
    displayName: 'Interest Received (Investing)',
    statementType: 'cash_flow',
    fieldGroup: 'investing',
    parentField: 'cash_from_investing',
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T5'],
  },

  // ── Equity Statement ──────────────────────────────────────
  {
    canonicalField: 'opening_equity',
    displayName: 'Opening Equity Balance',
    statementType: 'equity_statement',
    fieldGroup: 'equity_movement',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T5', 'T8'],
  },
  {
    canonicalField: 'dividends_paid',
    displayName: 'Dividends Declared / Paid',
    statementType: 'equity_statement',
    fieldGroup: 'equity_movement',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T3', 'T5', 'T8'],
  },
  {
    canonicalField: 'closing_equity',
    displayName: 'Closing Equity Balance',
    statementType: 'equity_statement',
    fieldGroup: 'equity_movement',
    parentField: null,
    formulaRule: 'opening_equity + total_comprehensive_income - dividends_paid',
    supportedTemplates: ['T1', 'T3', 'T5', 'T8'],
  },
  {
    canonicalField: 'weighted_avg_shares',
    displayName: 'Weighted Average Shares Outstanding',
    statementType: 'income_statement',
    fieldGroup: 'per_share',
    parentField: null,
    formulaRule: null,
    supportedTemplates: ['T1', 'T3'],
  },
];
