import type { TemplateRuleSet } from './types';

export const T3_IND_AS_NBFC: TemplateRuleSet = {
  templateType: 'T3',
  name: 'Ind AS / NBFC (India)',
  signals: ['Revenue from operations', 'Debenture redemption reserve', 'Reserve u/s 45-IC RBI', 'INR crore/lakh'],
  rules: [
    // ── Income Statement ──────────────────────────────────
    { normalizedLabel: 'revenue from operations', canonicalField: 'total_revenue', confidence: 0.98 },
    { normalizedLabel: 'interest income', canonicalField: 'interest_income', confidence: 0.98 },
    { normalizedLabel: 'interest earned', canonicalField: 'interest_income', confidence: 0.97 },
    { normalizedLabel: 'net interest income', canonicalField: 'net_interest_income', confidence: 0.97 },
    { normalizedLabel: 'fee and commission income', canonicalField: 'fee_income', confidence: 0.97 },
    { normalizedLabel: 'fees and commission income', canonicalField: 'fee_income', confidence: 0.97 },
    { normalizedLabel: 'net gain on fair value changes', canonicalField: 'other_operating_income', confidence: 0.90 },
    { normalizedLabel: 'net gain on derecognition of financial instruments', canonicalField: 'other_operating_income', confidence: 0.88 },
    { normalizedLabel: 'gain/loss on derivatives at fair value through profit or loss', canonicalField: 'other_operating_income', confidence: 0.85 },
    { normalizedLabel: 'other operating income', canonicalField: 'other_operating_income', confidence: 0.93 },
    { normalizedLabel: 'other income', canonicalField: 'other_income', confidence: 0.90 },
    { normalizedLabel: 'total income', canonicalField: 'total_income', confidence: 0.98 },
    { normalizedLabel: 'finance costs', canonicalField: 'finance_costs', confidence: 0.98 },
    { normalizedLabel: 'interest expense', canonicalField: 'finance_costs', confidence: 0.97 },
    { normalizedLabel: 'interest expended', canonicalField: 'finance_costs', confidence: 0.96 },
    { normalizedLabel: 'impairment on financial instruments', canonicalField: 'impairment_charge', confidence: 0.97 },
    { normalizedLabel: 'impairment loss on financial assets', canonicalField: 'impairment_charge', confidence: 0.96 },
    { normalizedLabel: 'provisions and write-offs', canonicalField: 'impairment_charge', confidence: 0.90 },
    { normalizedLabel: 'employee benefits expenses', canonicalField: 'employee_benefits_expense', confidence: 0.97 },
    { normalizedLabel: 'employee benefit expenses', canonicalField: 'employee_benefits_expense', confidence: 0.97 },
    { normalizedLabel: 'employee benefits expense', canonicalField: 'employee_benefits_expense', confidence: 0.97 },
    { normalizedLabel: 'staff costs', canonicalField: 'employee_benefits_expense', confidence: 0.93 },
    { normalizedLabel: 'depreciation and amortisation', canonicalField: 'depreciation_amortization', confidence: 0.97 },
    { normalizedLabel: 'depreciation amortisation and impairment', canonicalField: 'depreciation_amortization', confidence: 0.95 },
    { normalizedLabel: 'amortisation of borrowing issue costs included in finance cost', canonicalField: 'finance_costs', confidence: 0.85 },
    { normalizedLabel: 'other expenses', canonicalField: 'other_expenses', confidence: 0.92 },
    { normalizedLabel: 'total expenses', canonicalField: 'total_expenses', confidence: 0.98 },
    { normalizedLabel: 'profit before tax', canonicalField: 'profit_before_tax', confidence: 0.99 },
    { normalizedLabel: 'profit/(loss) before tax', canonicalField: 'profit_before_tax', confidence: 0.98 },
    { normalizedLabel: 'tax expense', canonicalField: 'income_tax_expense', confidence: 0.97 },
    { normalizedLabel: 'income tax expense', canonicalField: 'income_tax_expense', confidence: 0.98 },
    { normalizedLabel: 'current tax', canonicalField: 'income_tax_expense', confidence: 0.93 },
    { normalizedLabel: 'deferred tax', canonicalField: 'deferred_tax', confidence: 0.93 },
    { normalizedLabel: 'profit for the year', canonicalField: 'net_income', confidence: 0.98 },
    { normalizedLabel: 'profit for the period', canonicalField: 'net_income', confidence: 0.97 },
    { normalizedLabel: 'profit/(loss) for the year', canonicalField: 'net_income', confidence: 0.97 },
    { normalizedLabel: 'profit/(loss) for the period', canonicalField: 'net_income', confidence: 0.96 },

    // ── Other Comprehensive Income ────────────────────────
    { normalizedLabel: 'other comprehensive income', canonicalField: 'other_comprehensive_income', confidence: 0.97 },
    { normalizedLabel: 'items that will not be reclassified to profit or loss', canonicalField: 'other_comprehensive_income', confidence: 0.88 },
    { normalizedLabel: 'items that will be reclassified to profit or loss', canonicalField: 'other_comprehensive_income', confidence: 0.88 },
    { normalizedLabel: 'actuarial loss on defined benefit plan (gratuity) net of income tax', canonicalField: 'actuarial_gains_losses', confidence: 0.92 },
    { normalizedLabel: 'actuarial gain/loss on defined benefit plans', canonicalField: 'actuarial_gains_losses', confidence: 0.92 },
    { normalizedLabel: 'remeasurements of the defined benefit plans', canonicalField: 'actuarial_gains_losses', confidence: 0.90 },
    { normalizedLabel: 'total other comprehensive income', canonicalField: 'other_comprehensive_income', confidence: 0.95 },
    { normalizedLabel: 'total comprehensive income for the year', canonicalField: 'total_comprehensive_income', confidence: 0.98 },
    { normalizedLabel: 'total comprehensive income for the period', canonicalField: 'total_comprehensive_income', confidence: 0.97 },

    // ── EPS ───────────────────────────────────────────────
    { normalizedLabel: 'earnings per share basic', canonicalField: 'eps_basic', confidence: 0.97 },
    { normalizedLabel: 'earnings per share diluted', canonicalField: 'eps_diluted', confidence: 0.97 },
    { normalizedLabel: 'basic earnings per share', canonicalField: 'eps_basic', confidence: 0.97 },
    { normalizedLabel: 'diluted earnings per share', canonicalField: 'eps_diluted', confidence: 0.97 },

    // ── Balance Sheet — Assets ────────────────────────────
    { normalizedLabel: 'cash and cash equivalents', canonicalField: 'cash_and_equivalents', confidence: 0.99 },
    { normalizedLabel: 'bank balance other than above', canonicalField: 'bank_balances', confidence: 0.93 },
    { normalizedLabel: 'bank balance other than (a) above', canonicalField: 'bank_balances', confidence: 0.93 },
    { normalizedLabel: 'derivative financial instruments', canonicalField: 'derivative_assets', confidence: 0.92 },
    { normalizedLabel: 'receivables', canonicalField: 'trade_receivables', confidence: 0.90 },
    { normalizedLabel: 'trade receivables', canonicalField: 'trade_receivables', confidence: 0.97 },
    { normalizedLabel: 'loans', canonicalField: 'loans_and_advances', confidence: 0.90 },
    { normalizedLabel: 'loans and advances', canonicalField: 'loans_and_advances', confidence: 0.96 },
    { normalizedLabel: 'investments', canonicalField: 'investments', confidence: 0.93 },
    { normalizedLabel: 'other financial assets', canonicalField: 'other_financial_assets', confidence: 0.92 },
    { normalizedLabel: 'current tax assets (net)', canonicalField: 'current_tax_assets', confidence: 0.93 },
    { normalizedLabel: 'deferred tax assets (net)', canonicalField: 'deferred_tax_assets', confidence: 0.95 },
    { normalizedLabel: 'property plant and equipment', canonicalField: 'property_plant_equipment', confidence: 0.97 },
    { normalizedLabel: 'right-of-use assets', canonicalField: 'right_of_use_assets', confidence: 0.95 },
    { normalizedLabel: 'capital work-in-progress', canonicalField: 'capital_work_in_progress', confidence: 0.95 },
    { normalizedLabel: 'intangible assets', canonicalField: 'intangible_assets', confidence: 0.96 },
    { normalizedLabel: 'other non-financial assets', canonicalField: 'other_non_financial_assets', confidence: 0.92 },
    { normalizedLabel: 'total assets', canonicalField: 'total_assets', confidence: 0.99 },
    { normalizedLabel: 'financial assets', canonicalField: 'total_financial_assets', confidence: 0.88 },

    // ── Balance Sheet — Liabilities ───────────────────────
    { normalizedLabel: 'trade payables', canonicalField: 'trade_payables', confidence: 0.97 },
    { normalizedLabel: 'total outstanding dues of micro enterprises and small enterprises', canonicalField: 'trade_payables_msme', confidence: 0.97 },
    { normalizedLabel: 'total outstanding dues of creditors other than micro enterprises and small enterprises', canonicalField: 'trade_payables_other', confidence: 0.97 },
    { normalizedLabel: 'debt securities', canonicalField: 'debt_securities', confidence: 0.96 },
    { normalizedLabel: 'borrowings', canonicalField: 'borrowings', confidence: 0.97 },
    { normalizedLabel: 'subordinated liabilities', canonicalField: 'subordinated_debt', confidence: 0.95 },
    { normalizedLabel: 'other financial liabilities', canonicalField: 'other_financial_liabilities', confidence: 0.92 },
    { normalizedLabel: 'current tax liabilities (net)', canonicalField: 'current_tax_liabilities', confidence: 0.94 },
    { normalizedLabel: 'provisions', canonicalField: 'provisions', confidence: 0.93 },
    { normalizedLabel: 'other non-financial liabilities', canonicalField: 'other_non_financial_liabilities', confidence: 0.92 },
    { normalizedLabel: 'total liabilities', canonicalField: 'total_liabilities', confidence: 0.99 },
    { normalizedLabel: 'financial liabilities', canonicalField: 'total_financial_liabilities', confidence: 0.88 },

    // ── Balance Sheet — Equity ────────────────────────────
    { normalizedLabel: 'share capital', canonicalField: 'share_capital', confidence: 0.98 },
    { normalizedLabel: 'other equity', canonicalField: 'retained_earnings_and_reserves', confidence: 0.92 },
    { normalizedLabel: 'reserves and surplus', canonicalField: 'retained_earnings_and_reserves', confidence: 0.95 },
    { normalizedLabel: 'securities premium', canonicalField: 'share_premium', confidence: 0.96 },
    { normalizedLabel: 'securities premium account', canonicalField: 'share_premium', confidence: 0.96 },
    { normalizedLabel: 'retained earnings', canonicalField: 'retained_earnings', confidence: 0.98 },
    { normalizedLabel: 'statutory reserve u/s 45-ic of reserve bank of india act 1934', canonicalField: 'statutory_reserve_rbi', confidence: 0.99 },
    { normalizedLabel: 'reserve u/s 45-ic of reserve bank of india act 1934', canonicalField: 'statutory_reserve_rbi', confidence: 1.0 },
    { normalizedLabel: 'debenture redemption reserve', canonicalField: 'statutory_reserve_rbi', confidence: 0.90 },
    { normalizedLabel: 'general reserve', canonicalField: 'general_reserve', confidence: 0.95 },
    { normalizedLabel: 'capital reserve', canonicalField: 'capital_reserve', confidence: 0.95 },
    { normalizedLabel: 'total equity', canonicalField: 'total_equity', confidence: 0.99 },
    { normalizedLabel: 'equity share capital', canonicalField: 'share_capital', confidence: 0.97 },

    // ── Equity Statement rows ─────────────────────────────
    { normalizedLabel: 'balance at april 1, 2017', canonicalField: 'opening_equity', confidence: 0.90 },
    { normalizedLabel: 'balance at april 1, 2018', canonicalField: 'opening_equity', confidence: 0.90 },
    { normalizedLabel: 'balance at april 1, 2019', canonicalField: 'opening_equity', confidence: 0.90 },
    { normalizedLabel: 'balance at march 31, 2018', canonicalField: 'closing_equity', confidence: 0.90 },
    { normalizedLabel: 'balance at march 31, 2019', canonicalField: 'closing_equity', confidence: 0.90 },
    { normalizedLabel: 'balance at march 31, 2020', canonicalField: 'closing_equity', confidence: 0.90 },
    { normalizedLabel: 'profit for the year', canonicalField: 'net_income', confidence: 0.97 },
    { normalizedLabel: 'dividends paid', canonicalField: 'dividends_paid', confidence: 0.95 },
    { normalizedLabel: 'transfer to statutory reserve', canonicalField: 'statutory_reserve_rbi', confidence: 0.90 },
    { normalizedLabel: 'amalgamation adjustment account', canonicalField: 'amalgamation_reserve', confidence: 0.88 },
    { normalizedLabel: 'other comprehensive income for the year', canonicalField: 'other_comprehensive_income', confidence: 0.93 },

    // ── Equity Statement — additional rows ───────────────
    { normalizedLabel: 'issue of equity shares', canonicalField: 'share_capital', confidence: 0.90 },
    { normalizedLabel: 'capital redemption reserve', canonicalField: 'capital_reserve', confidence: 0.90 },
    { normalizedLabel: 'share issue expenses', canonicalField: 'share_premium', confidence: 0.85 },
    { normalizedLabel: 'tax on interim dividend', canonicalField: 'dividends_paid', confidence: 0.85 },
    { normalizedLabel: 'transfer to reserve u/s 36(1)(viii) of income tax act', canonicalField: 'general_reserve', confidence: 0.85 },
    { normalizedLabel: 'reserve u/s 36(1)(viii) of income tax act, 1961', canonicalField: 'general_reserve', confidence: 0.87 },
    { normalizedLabel: 'issued, subscribed and fully paid up equity shares outstanding at april 1, 2017', canonicalField: 'opening_equity', confidence: 0.88 },
    { normalizedLabel: 'issued, subscribed and fully paid up equity shares outstanding at april 1, 2018', canonicalField: 'opening_equity', confidence: 0.88 },
    { normalizedLabel: 'issued, subscribed and fully paid up equity shares outstanding at april 1, 2019', canonicalField: 'opening_equity', confidence: 0.88 },
    { normalizedLabel: 'issued, subscribed and fully paid up equity shares outstanding at the end of the year march 31, 2018', canonicalField: 'closing_equity', confidence: 0.88 },
    { normalizedLabel: 'issued, subscribed and fully paid up equity shares outstanding at the end of the year march 31, 2019', canonicalField: 'closing_equity', confidence: 0.88 },
    { normalizedLabel: 'issued, subscribed and fully paid up equity shares outstanding at the end of the year march 31, 2020', canonicalField: 'closing_equity', confidence: 0.88 },

    // ── Income Statement — loss/gain variants ────────────
    { normalizedLabel: 'net loss on fair value changes', canonicalField: 'other_operating_income', confidence: 0.90 },
    { normalizedLabel: 'net loss on derecognition of financial instruments under amortised cost category', canonicalField: 'other_operating_income', confidence: 0.88 },
    { normalizedLabel: 'fair value changes on loan assets', canonicalField: 'other_operating_income', confidence: 0.88 },
    { normalizedLabel: 'net loss on sale of property, plant and equipment', canonicalField: 'other_expenses', confidence: 0.87 },
    { normalizedLabel: '(gain)/loss on derivatives at fair value through profit or loss', canonicalField: 'other_operating_income', confidence: 0.85 },
    { normalizedLabel: 'rental income', canonicalField: 'other_income', confidence: 0.92 },
    { normalizedLabel: 'goodwill', canonicalField: 'intangible_assets', confidence: 0.88 },

    // ── Balance Sheet — additional ────────────────────────
    { normalizedLabel: 'trade and other payables', canonicalField: 'trade_payables', confidence: 0.90 },

    // ── Cash Flow ─────────────────────────────────────────
    { normalizedLabel: 'net cash from operating activities', canonicalField: 'net_cash_operating', confidence: 0.98 },
    { normalizedLabel: 'net cash used in operating activities', canonicalField: 'net_cash_operating', confidence: 0.98 },
    { normalizedLabel: 'net cash from investing activities', canonicalField: 'net_cash_investing', confidence: 0.98 },
    { normalizedLabel: 'net cash used in investing activities', canonicalField: 'net_cash_investing', confidence: 0.98 },
    { normalizedLabel: 'net cash from financing activities', canonicalField: 'net_cash_financing', confidence: 0.98 },
    { normalizedLabel: 'net cash used in financing activities', canonicalField: 'net_cash_financing', confidence: 0.98 },
    { normalizedLabel: 'cash and cash equivalents at the beginning of the year', canonicalField: 'cash_start', confidence: 0.97 },
    { normalizedLabel: 'cash and cash equivalents at the end of the year', canonicalField: 'cash_end', confidence: 0.97 },
    { normalizedLabel: 'net increase/(decrease) in cash and cash equivalents', canonicalField: 'net_cash_change', confidence: 0.95 },
    { normalizedLabel: 'amortisation of borrowing issue costs', canonicalField: 'finance_costs', confidence: 0.88 },
    { normalizedLabel: 'operating profit before working capital changes', canonicalField: 'cash_from_operations', confidence: 0.88 },
    { normalizedLabel: 'interest paid', canonicalField: 'finance_costs', confidence: 0.95 },
    { normalizedLabel: 'interest received', canonicalField: 'interest_income', confidence: 0.93 },
    { normalizedLabel: 'purchase of property, plant and equipment', canonicalField: 'capital_expenditure', confidence: 0.95 },
    { normalizedLabel: 'proceeds from sale of property, plant and equipment', canonicalField: 'proceeds_from_asset_disposal', confidence: 0.90 },
    { normalizedLabel: 'direct taxes refund/(paid)', canonicalField: 'income_tax_expense', confidence: 0.87 },
    { normalizedLabel: 'payment for issue costs', canonicalField: 'finance_costs', confidence: 0.85 },
    { normalizedLabel: 'payment for share issue costs', canonicalField: 'finance_costs', confidence: 0.85 },
    { normalizedLabel: 'change in other bank balance not available for immediate use', canonicalField: 'bank_balances', confidence: 0.85 },
  ],
};
