import type { TemplateRuleSet } from './types';

export const T5_UK_COMPANIES_ACT: TemplateRuleSet = {
  templateType: 'T5',
  name: 'UK Companies Act (Asset Manager)',
  signals: ['Turnover', 'Administration expenses', 'Operating (loss)/profit', 'Companies Act 2006'],
  rules: [
    { normalizedLabel: 'turnover', canonicalField: 'total_revenue', confidence: 0.98 },
    { normalizedLabel: 'cost of sales', canonicalField: 'cost_of_sales', confidence: 0.97 },
    { normalizedLabel: 'gross profit', canonicalField: 'gross_profit', confidence: 0.98 },
    { normalizedLabel: 'gross loss', canonicalField: 'gross_profit', confidence: 0.95 },
    { normalizedLabel: 'administrative expenses', canonicalField: 'admin_expenses', confidence: 0.97 },
    { normalizedLabel: 'administration expenses', canonicalField: 'admin_expenses', confidence: 0.97 },
    { normalizedLabel: 'other operating income', canonicalField: 'other_operating_income', confidence: 0.92 },
    { normalizedLabel: 'operating profit', canonicalField: 'operating_income', confidence: 0.95 },
    { normalizedLabel: 'operating loss', canonicalField: 'operating_income', confidence: 0.95 },
    { normalizedLabel: 'interest receivable', canonicalField: 'interest_income', confidence: 0.93 },
    { normalizedLabel: 'interest payable', canonicalField: 'finance_costs', confidence: 0.93 },
    { normalizedLabel: 'interest payable and similar charges', canonicalField: 'finance_costs', confidence: 0.95 },
    { normalizedLabel: 'profit before taxation', canonicalField: 'profit_before_tax', confidence: 0.97 },
    { normalizedLabel: 'loss before taxation', canonicalField: 'profit_before_tax', confidence: 0.97 },
    { normalizedLabel: 'taxation', canonicalField: 'income_tax_expense', confidence: 0.95 },
    { normalizedLabel: 'tax on profit', canonicalField: 'income_tax_expense', confidence: 0.95 },
    { normalizedLabel: 'tax on loss', canonicalField: 'income_tax_expense', confidence: 0.93 },
    { normalizedLabel: 'profit for the financial year', canonicalField: 'net_income', confidence: 0.98 },
    { normalizedLabel: 'loss for the financial year', canonicalField: 'net_income', confidence: 0.98 },
    { normalizedLabel: 'net profit for the year', canonicalField: 'net_income', confidence: 0.97 },
    { normalizedLabel: 'net loss for the year', canonicalField: 'net_income', confidence: 0.97 },
    { normalizedLabel: 'total assets', canonicalField: 'total_assets', confidence: 0.99 },
    { normalizedLabel: 'net assets', canonicalField: 'total_equity', confidence: 0.93 },
    { normalizedLabel: 'called up share capital', canonicalField: 'share_capital', confidence: 0.95 },
    { normalizedLabel: 'profit and loss account', canonicalField: 'retained_earnings', confidence: 0.93 },
    { normalizedLabel: 'shareholders funds', canonicalField: 'total_equity', confidence: 0.97 },
  ],
};
